/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TracesIndexRouteImport } from './routes/traces/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as McpIndexRouteImport } from './routes/mcp/index'
import { Route as InboxIndexRouteImport } from './routes/inbox/index'
import { Route as EvalsIndexRouteImport } from './routes/evals/index'
import { Route as DatasetsIndexRouteImport } from './routes/datasets/index'
import { Route as ChangelogIndexRouteImport } from './routes/changelog/index'
import { Route as TracesTraceIdRouteImport } from './routes/traces/$traceId'
import { Route as TasksTaskKeyRouteImport } from './routes/tasks/$taskKey'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as EvalsEvalIdRouteImport } from './routes/evals/$evalId'
import { Route as DatasetsDatasetIdRouteImport } from './routes/datasets/$datasetId'
import { Route as InventorySystemPromptsIndexRouteImport } from './routes/inventory/system-prompts/index'
import { Route as InventorySystemPromptsPromptIdRouteImport } from './routes/inventory/system-prompts/$promptId'
import { Route as EvalsRunsRunIdRouteImport } from './routes/evals/runs.$runId'
import { Route as ApiEvalsIngestRouteImport } from './routes/api/evals/ingest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesIndexRoute = TracesIndexRouteImport.update({
  id: '/traces/',
  path: '/traces/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const McpIndexRoute = McpIndexRouteImport.update({
  id: '/mcp/',
  path: '/mcp/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalsIndexRoute = EvalsIndexRouteImport.update({
  id: '/evals/',
  path: '/evals/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsIndexRoute = DatasetsIndexRouteImport.update({
  id: '/datasets/',
  path: '/datasets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesTraceIdRoute = TracesTraceIdRouteImport.update({
  id: '/traces/$traceId',
  path: '/traces/$traceId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskKeyRoute = TasksTaskKeyRouteImport.update({
  id: '/tasks/$taskKey',
  path: '/tasks/$taskKey',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalsEvalIdRoute = EvalsEvalIdRouteImport.update({
  id: '/evals/$evalId',
  path: '/evals/$evalId',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsDatasetIdRoute = DatasetsDatasetIdRouteImport.update({
  id: '/datasets/$datasetId',
  path: '/datasets/$datasetId',
  getParentRoute: () => rootRouteImport,
} as any)
const InventorySystemPromptsIndexRoute =
  InventorySystemPromptsIndexRouteImport.update({
    id: '/inventory/system-prompts/',
    path: '/inventory/system-prompts/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InventorySystemPromptsPromptIdRoute =
  InventorySystemPromptsPromptIdRouteImport.update({
    id: '/inventory/system-prompts/$promptId',
    path: '/inventory/system-prompts/$promptId',
    getParentRoute: () => rootRouteImport,
  } as any)
const EvalsRunsRunIdRoute = EvalsRunsRunIdRouteImport.update({
  id: '/evals/runs/$runId',
  path: '/evals/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvalsIngestRoute = ApiEvalsIngestRouteImport.update({
  id: '/api/evals/ingest',
  path: '/api/evals/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/evals/$evalId': typeof EvalsEvalIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/tasks/$taskKey': typeof TasksTaskKeyRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/evals/': typeof EvalsIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/mcp/': typeof McpIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/traces/': typeof TracesIndexRoute
  '/api/evals/ingest': typeof ApiEvalsIngestRoute
  '/evals/runs/$runId': typeof EvalsRunsRunIdRoute
  '/inventory/system-prompts/$promptId': typeof InventorySystemPromptsPromptIdRoute
  '/inventory/system-prompts/': typeof InventorySystemPromptsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/evals/$evalId': typeof EvalsEvalIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/tasks/$taskKey': typeof TasksTaskKeyRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/changelog': typeof ChangelogIndexRoute
  '/datasets': typeof DatasetsIndexRoute
  '/evals': typeof EvalsIndexRoute
  '/inbox': typeof InboxIndexRoute
  '/mcp': typeof McpIndexRoute
  '/notes': typeof NotesIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/traces': typeof TracesIndexRoute
  '/api/evals/ingest': typeof ApiEvalsIngestRoute
  '/evals/runs/$runId': typeof EvalsRunsRunIdRoute
  '/inventory/system-prompts/$promptId': typeof InventorySystemPromptsPromptIdRoute
  '/inventory/system-prompts': typeof InventorySystemPromptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/evals/$evalId': typeof EvalsEvalIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/tasks/$taskKey': typeof TasksTaskKeyRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/evals/': typeof EvalsIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/mcp/': typeof McpIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/traces/': typeof TracesIndexRoute
  '/api/evals/ingest': typeof ApiEvalsIngestRoute
  '/evals/runs/$runId': typeof EvalsRunsRunIdRoute
  '/inventory/system-prompts/$promptId': typeof InventorySystemPromptsPromptIdRoute
  '/inventory/system-prompts/': typeof InventorySystemPromptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datasets/$datasetId'
    | '/evals/$evalId'
    | '/sessions/$sessionId'
    | '/tasks/$taskKey'
    | '/traces/$traceId'
    | '/changelog/'
    | '/datasets/'
    | '/evals/'
    | '/inbox/'
    | '/mcp/'
    | '/notes/'
    | '/sessions/'
    | '/tasks/'
    | '/tools/'
    | '/traces/'
    | '/api/evals/ingest'
    | '/evals/runs/$runId'
    | '/inventory/system-prompts/$promptId'
    | '/inventory/system-prompts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datasets/$datasetId'
    | '/evals/$evalId'
    | '/sessions/$sessionId'
    | '/tasks/$taskKey'
    | '/traces/$traceId'
    | '/changelog'
    | '/datasets'
    | '/evals'
    | '/inbox'
    | '/mcp'
    | '/notes'
    | '/sessions'
    | '/tasks'
    | '/tools'
    | '/traces'
    | '/api/evals/ingest'
    | '/evals/runs/$runId'
    | '/inventory/system-prompts/$promptId'
    | '/inventory/system-prompts'
  id:
    | '__root__'
    | '/'
    | '/datasets/$datasetId'
    | '/evals/$evalId'
    | '/sessions/$sessionId'
    | '/tasks/$taskKey'
    | '/traces/$traceId'
    | '/changelog/'
    | '/datasets/'
    | '/evals/'
    | '/inbox/'
    | '/mcp/'
    | '/notes/'
    | '/sessions/'
    | '/tasks/'
    | '/tools/'
    | '/traces/'
    | '/api/evals/ingest'
    | '/evals/runs/$runId'
    | '/inventory/system-prompts/$promptId'
    | '/inventory/system-prompts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatasetsDatasetIdRoute: typeof DatasetsDatasetIdRoute
  EvalsEvalIdRoute: typeof EvalsEvalIdRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  TasksTaskKeyRoute: typeof TasksTaskKeyRoute
  TracesTraceIdRoute: typeof TracesTraceIdRoute
  ChangelogIndexRoute: typeof ChangelogIndexRoute
  DatasetsIndexRoute: typeof DatasetsIndexRoute
  EvalsIndexRoute: typeof EvalsIndexRoute
  InboxIndexRoute: typeof InboxIndexRoute
  McpIndexRoute: typeof McpIndexRoute
  NotesIndexRoute: typeof NotesIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  TracesIndexRoute: typeof TracesIndexRoute
  ApiEvalsIngestRoute: typeof ApiEvalsIngestRoute
  EvalsRunsRunIdRoute: typeof EvalsRunsRunIdRoute
  InventorySystemPromptsPromptIdRoute: typeof InventorySystemPromptsPromptIdRoute
  InventorySystemPromptsIndexRoute: typeof InventorySystemPromptsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/': {
      id: '/traces/'
      path: '/traces'
      fullPath: '/traces/'
      preLoaderRoute: typeof TracesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/': {
      id: '/mcp/'
      path: '/mcp'
      fullPath: '/mcp/'
      preLoaderRoute: typeof McpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evals/': {
      id: '/evals/'
      path: '/evals'
      fullPath: '/evals/'
      preLoaderRoute: typeof EvalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/': {
      id: '/datasets/'
      path: '/datasets'
      fullPath: '/datasets/'
      preLoaderRoute: typeof DatasetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/': {
      id: '/changelog/'
      path: '/changelog'
      fullPath: '/changelog/'
      preLoaderRoute: typeof ChangelogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/$traceId': {
      id: '/traces/$traceId'
      path: '/traces/$traceId'
      fullPath: '/traces/$traceId'
      preLoaderRoute: typeof TracesTraceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskKey': {
      id: '/tasks/$taskKey'
      path: '/tasks/$taskKey'
      fullPath: '/tasks/$taskKey'
      preLoaderRoute: typeof TasksTaskKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evals/$evalId': {
      id: '/evals/$evalId'
      path: '/evals/$evalId'
      fullPath: '/evals/$evalId'
      preLoaderRoute: typeof EvalsEvalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/$datasetId': {
      id: '/datasets/$datasetId'
      path: '/datasets/$datasetId'
      fullPath: '/datasets/$datasetId'
      preLoaderRoute: typeof DatasetsDatasetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/system-prompts/': {
      id: '/inventory/system-prompts/'
      path: '/inventory/system-prompts'
      fullPath: '/inventory/system-prompts/'
      preLoaderRoute: typeof InventorySystemPromptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/system-prompts/$promptId': {
      id: '/inventory/system-prompts/$promptId'
      path: '/inventory/system-prompts/$promptId'
      fullPath: '/inventory/system-prompts/$promptId'
      preLoaderRoute: typeof InventorySystemPromptsPromptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evals/runs/$runId': {
      id: '/evals/runs/$runId'
      path: '/evals/runs/$runId'
      fullPath: '/evals/runs/$runId'
      preLoaderRoute: typeof EvalsRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evals/ingest': {
      id: '/api/evals/ingest'
      path: '/api/evals/ingest'
      fullPath: '/api/evals/ingest'
      preLoaderRoute: typeof ApiEvalsIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatasetsDatasetIdRoute: DatasetsDatasetIdRoute,
  EvalsEvalIdRoute: EvalsEvalIdRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  TasksTaskKeyRoute: TasksTaskKeyRoute,
  TracesTraceIdRoute: TracesTraceIdRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
  DatasetsIndexRoute: DatasetsIndexRoute,
  EvalsIndexRoute: EvalsIndexRoute,
  InboxIndexRoute: InboxIndexRoute,
  McpIndexRoute: McpIndexRoute,
  NotesIndexRoute: NotesIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  TracesIndexRoute: TracesIndexRoute,
  ApiEvalsIngestRoute: ApiEvalsIngestRoute,
  EvalsRunsRunIdRoute: EvalsRunsRunIdRoute,
  InventorySystemPromptsPromptIdRoute: InventorySystemPromptsPromptIdRoute,
  InventorySystemPromptsIndexRoute: InventorySystemPromptsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
