/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TracesIndexRouteImport } from './routes/traces/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as McpIndexRouteImport } from './routes/mcp/index'
import { Route as InboxIndexRouteImport } from './routes/inbox/index'
import { Route as EvalsIndexRouteImport } from './routes/evals/index'
import { Route as TracesTraceIdRouteImport } from './routes/traces/$traceId'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesIndexRoute = TracesIndexRouteImport.update({
  id: '/traces/',
  path: '/traces/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const McpIndexRoute = McpIndexRouteImport.update({
  id: '/mcp/',
  path: '/mcp/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalsIndexRoute = EvalsIndexRouteImport.update({
  id: '/evals/',
  path: '/evals/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesTraceIdRoute = TracesTraceIdRouteImport.update({
  id: '/traces/$traceId',
  path: '/traces/$traceId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/evals/': typeof EvalsIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/mcp/': typeof McpIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/traces/': typeof TracesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/evals': typeof EvalsIndexRoute
  '/inbox': typeof InboxIndexRoute
  '/mcp': typeof McpIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/traces': typeof TracesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/evals/': typeof EvalsIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/mcp/': typeof McpIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/traces/': typeof TracesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sessions/$sessionId'
    | '/traces/$traceId'
    | '/evals/'
    | '/inbox/'
    | '/mcp/'
    | '/sessions/'
    | '/traces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sessions/$sessionId'
    | '/traces/$traceId'
    | '/evals'
    | '/inbox'
    | '/mcp'
    | '/sessions'
    | '/traces'
  id:
    | '__root__'
    | '/'
    | '/sessions/$sessionId'
    | '/traces/$traceId'
    | '/evals/'
    | '/inbox/'
    | '/mcp/'
    | '/sessions/'
    | '/traces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  TracesTraceIdRoute: typeof TracesTraceIdRoute
  EvalsIndexRoute: typeof EvalsIndexRoute
  InboxIndexRoute: typeof InboxIndexRoute
  McpIndexRoute: typeof McpIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  TracesIndexRoute: typeof TracesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/': {
      id: '/traces/'
      path: '/traces'
      fullPath: '/traces/'
      preLoaderRoute: typeof TracesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/': {
      id: '/mcp/'
      path: '/mcp'
      fullPath: '/mcp/'
      preLoaderRoute: typeof McpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evals/': {
      id: '/evals/'
      path: '/evals'
      fullPath: '/evals/'
      preLoaderRoute: typeof EvalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/$traceId': {
      id: '/traces/$traceId'
      path: '/traces/$traceId'
      fullPath: '/traces/$traceId'
      preLoaderRoute: typeof TracesTraceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  TracesTraceIdRoute: TracesTraceIdRoute,
  EvalsIndexRoute: EvalsIndexRoute,
  InboxIndexRoute: InboxIndexRoute,
  McpIndexRoute: McpIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  TracesIndexRoute: TracesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
