/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaletteRouteImport } from './routes/palette'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as McpIndexRouteImport } from './routes/mcp/index'
import { Route as LiveIndexRouteImport } from './routes/live/index'
import { Route as InboxIndexRouteImport } from './routes/inbox/index'
import { Route as EvalsIndexRouteImport } from './routes/evals/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as RunsRunIdRouteImport } from './routes/runs/$runId'
import { Route as LiveRunIdRouteImport } from './routes/live/$runId'

const PaletteRoute = PaletteRouteImport.update({
  id: '/palette',
  path: '/palette',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const McpIndexRoute = McpIndexRouteImport.update({
  id: '/mcp/',
  path: '/mcp/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIndexRoute = LiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalsIndexRoute = EvalsIndexRouteImport.update({
  id: '/evals/',
  path: '/evals/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRunIdRoute = LiveRunIdRouteImport.update({
  id: '/live/$runId',
  path: '/live/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/palette': typeof PaletteRoute
  '/live/$runId': typeof LiveRunIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/evals/': typeof EvalsIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/live/': typeof LiveIndexRoute
  '/mcp/': typeof McpIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/palette': typeof PaletteRoute
  '/live/$runId': typeof LiveRunIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/evals': typeof EvalsIndexRoute
  '/inbox': typeof InboxIndexRoute
  '/live': typeof LiveIndexRoute
  '/mcp': typeof McpIndexRoute
  '/runs': typeof RunsIndexRoute
  '/sessions': typeof SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/palette': typeof PaletteRoute
  '/live/$runId': typeof LiveRunIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/evals/': typeof EvalsIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/live/': typeof LiveIndexRoute
  '/mcp/': typeof McpIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/palette'
    | '/live/$runId'
    | '/runs/$runId'
    | '/sessions/$sessionId'
    | '/evals/'
    | '/inbox/'
    | '/live/'
    | '/mcp/'
    | '/runs/'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/palette'
    | '/live/$runId'
    | '/runs/$runId'
    | '/sessions/$sessionId'
    | '/evals'
    | '/inbox'
    | '/live'
    | '/mcp'
    | '/runs'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/palette'
    | '/live/$runId'
    | '/runs/$runId'
    | '/sessions/$sessionId'
    | '/evals/'
    | '/inbox/'
    | '/live/'
    | '/mcp/'
    | '/runs/'
    | '/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PaletteRoute: typeof PaletteRoute
  LiveRunIdRoute: typeof LiveRunIdRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  EvalsIndexRoute: typeof EvalsIndexRoute
  InboxIndexRoute: typeof InboxIndexRoute
  LiveIndexRoute: typeof LiveIndexRoute
  McpIndexRoute: typeof McpIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/palette': {
      id: '/palette'
      path: '/palette'
      fullPath: '/palette'
      preLoaderRoute: typeof PaletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/': {
      id: '/mcp/'
      path: '/mcp'
      fullPath: '/mcp/'
      preLoaderRoute: typeof McpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/': {
      id: '/live/'
      path: '/live'
      fullPath: '/live/'
      preLoaderRoute: typeof LiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evals/': {
      id: '/evals/'
      path: '/evals'
      fullPath: '/evals/'
      preLoaderRoute: typeof EvalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$runId': {
      id: '/live/$runId'
      path: '/live/$runId'
      fullPath: '/live/$runId'
      preLoaderRoute: typeof LiveRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PaletteRoute: PaletteRoute,
  LiveRunIdRoute: LiveRunIdRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  EvalsIndexRoute: EvalsIndexRoute,
  InboxIndexRoute: InboxIndexRoute,
  LiveIndexRoute: LiveIndexRoute,
  McpIndexRoute: McpIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
